-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alunos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  escola_id uuid,
  responsavel_id uuid,
  nome_completo text NOT NULL,
  data_nascimento date,
  turma_atual text,
  matricula_escolar text,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  nome_mae text,
  telefone_mae text,
  nome_pai text,
  telefone_pai text,
  restricoes_alimentares text,
  observacoes_pedagogicas text,
  valor_mensalidade numeric DEFAULT 0.00 CHECK (valor_mensalidade >= 0::numeric),
  turma_id uuid,
  email_contato_pai text,
  email_contato_mae text,
  celular_contato_pai text,
  celular_contato_mae text,
  senha_acesso_portal text,
  foto_url text,
  turno_contratado text DEFAULT 'Manhã'::text CHECK (turno_contratado = ANY (ARRAY['Manhã'::text, 'Tarde'::text, 'Integral'::text])),
  desconto_percentual numeric DEFAULT 0,
  dia_vencimento integer DEFAULT 10,
  naturalidade text,
  uf_nascimento text,
  nacionalidade text DEFAULT 'Brasileira'::text,
  rg_numero text,
  cpf_aluno text,
  carteira_sus text,
  tipo_sanguineo text,
  possui_necessidade_especial boolean DEFAULT false,
  cid_necessidade text,
  remedios_continuos text,
  plano_saude text,
  autoriza_imagem boolean DEFAULT true,
  restrucao_judicial text,
  responsavel_pedagogico text,
  CONSTRAINT alunos_pkey PRIMARY KEY (id),
  CONSTRAINT alunos_escola_id_fkey FOREIGN KEY (escola_id) REFERENCES public.escolas(id),
  CONSTRAINT alunos_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES public.responsaveis(id),
  CONSTRAINT alunos_turma_id_fkey FOREIGN KEY (turma_id) REFERENCES public.turmas(id)
);
CREATE TABLE public.autorizados_buscar (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  escola_id uuid,
  aluno_id uuid,
  nome_completo text NOT NULL,
  parentesco text NOT NULL,
  cpf text,
  telefone text,
  foto_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT autorizados_buscar_pkey PRIMARY KEY (id),
  CONSTRAINT autorizados_buscar_escola_id_fkey FOREIGN KEY (escola_id) REFERENCES public.escolas(id),
  CONSTRAINT autorizados_buscar_aluno_id_fkey FOREIGN KEY (aluno_id) REFERENCES public.alunos(id)
);
CREATE TABLE public.cobrancas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  escola_id uuid,
  aluno_id uuid,
  responsavel_id uuid,
  valor_original numeric NOT NULL CHECK (valor_original >= 0::numeric),
  data_vencimento date NOT NULL,
  descricao text,
  status text DEFAULT 'PENDENTE'::text CHECK (status = ANY (ARRAY['PENDENTE'::text, 'PAGO'::text, 'ATRASADO'::text, 'CANCELADO'::text, 'PARCIAL'::text])),
  asaas_cobranca_id text,
  asaas_url_pagamento text,
  data_pagamento timestamp with time zone,
  valor_pago numeric,
  nota_fiscal_emitida boolean DEFAULT false,
  link_nota_fiscal text,
  created_at timestamp with time zone DEFAULT now(),
  forma_pagamento text,
  observacao text,
  CONSTRAINT cobrancas_pkey PRIMARY KEY (id),
  CONSTRAINT cobrancas_escola_id_fkey FOREIGN KEY (escola_id) REFERENCES public.escolas(id),
  CONSTRAINT cobrancas_aluno_id_fkey FOREIGN KEY (aluno_id) REFERENCES public.alunos(id),
  CONSTRAINT cobrancas_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES public.responsaveis(id)
);
CREATE TABLE public.escolas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome_fantasia text NOT NULL,
  razao_social text,
  cnpj text UNIQUE,
  email_contato text,
  telefone_suporte text,
  created_at timestamp with time zone DEFAULT now(),
  logo_url text,
  endereco_rua text,
  endereco_numero text,
  endereco_bairro text,
  endereco_cidade text,
  endereco_uf text,
  endereco_cep text,
  multa_atraso_valor numeric DEFAULT 0.25,
  juros_mensal_percentual numeric DEFAULT 1.00,
  desconto_pontualidade numeric DEFAULT 7.00,
  dia_limite_desconto integer DEFAULT 5,
  desconto_irmaos_percentual numeric DEFAULT 10.00,
  CONSTRAINT escolas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.logs_atividades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  data_hora timestamp with time zone DEFAULT now(),
  usuario text,
  acao text,
  detalhes text,
  entidade_afetada text,
  dados_tecnicos jsonb,
  CONSTRAINT logs_atividades_pkey PRIMARY KEY (id)
);
CREATE TABLE public.responsaveis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  escola_id uuid,
  nome_completo text NOT NULL,
  cpf text NOT NULL UNIQUE,
  email text NOT NULL,
  telefone_celular text NOT NULL,
  endereco_rua text,
  endereco_numero text,
  endereco_bairro text,
  endereco_cep text,
  asaas_customer_id text,
  created_at timestamp with time zone DEFAULT now(),
  endereco_cidade text,
  endereco_uf text,
  nome_secundario text,
  cpf_secundario text,
  celular_secundario text,
  email_secundario text,
  foto_url text,
  rg text,
  profissao text,
  local_trabalho text,
  telefone_comercial text,
  escolaridade text,
  rg_secundario text,
  escolaridade_secundario text,
  profissao_secundario text,
  CONSTRAINT responsaveis_pkey PRIMARY KEY (id),
  CONSTRAINT responsaveis_escola_id_fkey FOREIGN KEY (escola_id) REFERENCES public.escolas(id)
);
CREATE TABLE public.solicitacoes_alteracao (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'PENDENTE'::text,
  tipo_entidade text NOT NULL,
  entidade_id uuid NOT NULL,
  dados_novos jsonb NOT NULL,
  mensagem_pai text,
  CONSTRAINT solicitacoes_alteracao_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tabela_precos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  escola_id uuid,
  ano_letivo integer DEFAULT 2026,
  nivel text NOT NULL,
  turno text NOT NULL,
  valor_matricula numeric DEFAULT 0,
  valor_mensalidade numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  valor_janeiro numeric DEFAULT 0,
  CONSTRAINT tabela_precos_pkey PRIMARY KEY (id),
  CONSTRAINT tabela_precos_escola_id_fkey FOREIGN KEY (escola_id) REFERENCES public.escolas(id)
);
CREATE TABLE public.transacoes_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  escola_id uuid NOT NULL,
  cobranca_id uuid,
  responsavel_id uuid,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['DEBITO_MENSALIDADE'::text, 'BAIXA_PAGAMENTO'::text, 'ESTORNO'::text, 'MULTA'::text, 'DESCONTO'::text])),
  valor numeric NOT NULL,
  usuario_responsavel uuid,
  detalhes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transacoes_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT transacoes_ledger_escola_id_fkey FOREIGN KEY (escola_id) REFERENCES public.escolas(id),
  CONSTRAINT transacoes_ledger_cobranca_id_fkey FOREIGN KEY (cobranca_id) REFERENCES public.cobrancas(id),
  CONSTRAINT transacoes_ledger_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES public.responsaveis(id),
  CONSTRAINT transacoes_ledger_usuario_responsavel_fkey FOREIGN KEY (usuario_responsavel) REFERENCES auth.users(id)
);
CREATE TABLE public.turmas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  escola_id uuid,
  nome text NOT NULL,
  nivel text NOT NULL,
  ano_letivo integer DEFAULT 2025,
  created_at timestamp with time zone DEFAULT now(),
  capacidade integer DEFAULT 30,
  turno text DEFAULT 'Manhã'::text CHECK (turno = ANY (ARRAY['Manhã'::text, 'Tarde'::text, 'Integral'::text])),
  CONSTRAINT turmas_pkey PRIMARY KEY (id),
  CONSTRAINT turmas_escola_id_fkey FOREIGN KEY (escola_id) REFERENCES public.escolas(id)
);
CREATE TABLE public.users_profiles (
  id uuid NOT NULL,
  escola_id uuid,
  email text,
  nome_completo text,
  created_at timestamp with time zone DEFAULT now(),
  roles ARRAY DEFAULT '{responsavel}'::app_role[],
  is_superuser boolean DEFAULT false,
  CONSTRAINT users_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT users_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_profiles_escola_id_fkey FOREIGN KEY (escola_id) REFERENCES public.escolas(id)
);